//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input Management/Input Actions/TempInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TempInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TempInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TempInputs"",
    ""maps"": [
        {
            ""name"": ""general"",
            ""id"": ""23f8f251-1c2a-4b1d-a1c2-945f27b5284a"",
            ""actions"": [
                {
                    ""name"": ""action"",
                    ""type"": ""Value"",
                    ""id"": ""05a270dc-e336-48c4-8fb7-51e654a20e39"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""cancel"",
                    ""type"": ""Value"",
                    ""id"": ""104688f0-bdbb-4bb6-9636-6e0ebabbb465"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""buttonWest"",
                    ""type"": ""Button"",
                    ""id"": ""4e83ef54-63f0-4a3c-a552-28f78a1e1648"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonNorth"",
                    ""type"": ""Button"",
                    ""id"": ""5ff0acf0-3029-437c-b3b2-cf4c92320db1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonEast"",
                    ""type"": ""Button"",
                    ""id"": ""c6e1e4ac-2d32-441d-a103-a0298b9ab866"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""oneKey"",
                    ""type"": ""Button"",
                    ""id"": ""2a65a149-44e6-46da-9eea-862c4f8544e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""twoKey"",
                    ""type"": ""Button"",
                    ""id"": ""aefeffc2-8d57-4aef-b4fb-4c6c415e3c8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""threeKey"",
                    ""type"": ""Button"",
                    ""id"": ""1c543a1b-6ef3-4fd8-9634-a2339eb061ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fourKey"",
                    ""type"": ""Button"",
                    ""id"": ""f5d15249-60b1-43bf-9df2-0da04b0cd15f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""space"",
                    ""type"": ""Button"",
                    ""id"": ""fe35796e-dc4d-45e7-9377-a0394a7777a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""f_Key"",
                    ""type"": ""Button"",
                    ""id"": ""c1f310a2-6593-4b7e-b9b6-7537ce1248dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""g_key"",
                    ""type"": ""Button"",
                    ""id"": ""820ea945-9bc8-4bc1-8704-f69bdcd0e04c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""t_key"",
                    ""type"": ""Button"",
                    ""id"": ""5ee3271f-e8be-41b1-a48e-a1ca41cbb767"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""i_key"",
                    ""type"": ""Button"",
                    ""id"": ""aae7f598-c76b-4dff-a857-824f4c3f881b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""b_key"",
                    ""type"": ""Button"",
                    ""id"": ""ea39a3df-516a-4a96-89cf-836ec4f78b02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""m_key"",
                    ""type"": ""Button"",
                    ""id"": ""eb469908-7d39-4865-8077-9adaf2283981"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""n_key"",
                    ""type"": ""Button"",
                    ""id"": ""29415104-2a94-4c78-9e37-ee57d41442ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""x_key"",
                    ""type"": ""Button"",
                    ""id"": ""ad7bee2c-e748-48fa-ad1c-bcac31de57b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""c_key"",
                    ""type"": ""Button"",
                    ""id"": ""ba7a15be-3108-4709-ae96-038dfaaef286"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""v_key"",
                    ""type"": ""Button"",
                    ""id"": ""bdd38844-c2b7-4434-a627-13a0e04f29ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6b5a7330-d25a-4ff7-b99d-fa56186dd479"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aa2d5a0-a0c2-4421-899b-7aeec4198783"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a193d20e-634f-47df-8714-e1790e497d79"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ecce777-e1f4-48b7-974e-6b32759f1878"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b94eca74-f429-4d92-b4da-f20088b38618"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""414ebb04-b1a2-43e4-891a-46e7176b6199"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80347876-490a-4cdc-8743-fff2492124a4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28b0f0c3-570f-4bf6-b1a0-a26e6e11939f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""283bbd48-2935-4e84-9b98-93d04d1af8a9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fd79650-9924-4ab5-81f1-6f310358a043"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9771d224-acc4-40d0-9b71-d2b4518625a6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""oneKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d1dd23a-e255-4d78-924f-78a6bdac0de1"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""twoKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2019d2f-6f20-4afd-8e9b-28e57a6e4d25"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""threeKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3596a12-9554-4ebc-8f4b-5dec8a746bdd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7046bd68-8dc5-4a19-9575-8e53a13ddea2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fourKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c00a0073-2529-4a10-af03-0be2282a8602"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""g_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55e747de-7792-40a6-b3f6-92654af6f1cf"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""f_Key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b3df21f-953b-43b1-809c-b457eec7ea89"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""t_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ac0bd77-9ba6-4f06-afc0-685fa45c8595"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""i_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c3f7709-4473-426b-89fa-d4e8668a996d"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""b_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04ecc7ca-d904-4032-b01d-71b4f426d431"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""m_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dffd32d6-02ea-413d-af82-fe52aff41b7e"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""n_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""255c44ba-f611-42d1-8bcd-53fed3925f6c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""x_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be3d3673-281f-4d8f-b34d-9c65789b2196"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""c_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""672cf5b3-e3c0-4419-83ec-043ad325ca6d"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""v_key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // general
        m_general = asset.FindActionMap("general", throwIfNotFound: true);
        m_general_action = m_general.FindAction("action", throwIfNotFound: true);
        m_general_cancel = m_general.FindAction("cancel", throwIfNotFound: true);
        m_general_buttonWest = m_general.FindAction("buttonWest", throwIfNotFound: true);
        m_general_buttonNorth = m_general.FindAction("buttonNorth", throwIfNotFound: true);
        m_general_buttonEast = m_general.FindAction("buttonEast", throwIfNotFound: true);
        m_general_oneKey = m_general.FindAction("oneKey", throwIfNotFound: true);
        m_general_twoKey = m_general.FindAction("twoKey", throwIfNotFound: true);
        m_general_threeKey = m_general.FindAction("threeKey", throwIfNotFound: true);
        m_general_fourKey = m_general.FindAction("fourKey", throwIfNotFound: true);
        m_general_space = m_general.FindAction("space", throwIfNotFound: true);
        m_general_f_Key = m_general.FindAction("f_Key", throwIfNotFound: true);
        m_general_g_key = m_general.FindAction("g_key", throwIfNotFound: true);
        m_general_t_key = m_general.FindAction("t_key", throwIfNotFound: true);
        m_general_i_key = m_general.FindAction("i_key", throwIfNotFound: true);
        m_general_b_key = m_general.FindAction("b_key", throwIfNotFound: true);
        m_general_m_key = m_general.FindAction("m_key", throwIfNotFound: true);
        m_general_n_key = m_general.FindAction("n_key", throwIfNotFound: true);
        m_general_x_key = m_general.FindAction("x_key", throwIfNotFound: true);
        m_general_c_key = m_general.FindAction("c_key", throwIfNotFound: true);
        m_general_v_key = m_general.FindAction("v_key", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // general
    private readonly InputActionMap m_general;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_general_action;
    private readonly InputAction m_general_cancel;
    private readonly InputAction m_general_buttonWest;
    private readonly InputAction m_general_buttonNorth;
    private readonly InputAction m_general_buttonEast;
    private readonly InputAction m_general_oneKey;
    private readonly InputAction m_general_twoKey;
    private readonly InputAction m_general_threeKey;
    private readonly InputAction m_general_fourKey;
    private readonly InputAction m_general_space;
    private readonly InputAction m_general_f_Key;
    private readonly InputAction m_general_g_key;
    private readonly InputAction m_general_t_key;
    private readonly InputAction m_general_i_key;
    private readonly InputAction m_general_b_key;
    private readonly InputAction m_general_m_key;
    private readonly InputAction m_general_n_key;
    private readonly InputAction m_general_x_key;
    private readonly InputAction m_general_c_key;
    private readonly InputAction m_general_v_key;
    public struct GeneralActions
    {
        private @TempInputs m_Wrapper;
        public GeneralActions(@TempInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @action => m_Wrapper.m_general_action;
        public InputAction @cancel => m_Wrapper.m_general_cancel;
        public InputAction @buttonWest => m_Wrapper.m_general_buttonWest;
        public InputAction @buttonNorth => m_Wrapper.m_general_buttonNorth;
        public InputAction @buttonEast => m_Wrapper.m_general_buttonEast;
        public InputAction @oneKey => m_Wrapper.m_general_oneKey;
        public InputAction @twoKey => m_Wrapper.m_general_twoKey;
        public InputAction @threeKey => m_Wrapper.m_general_threeKey;
        public InputAction @fourKey => m_Wrapper.m_general_fourKey;
        public InputAction @space => m_Wrapper.m_general_space;
        public InputAction @f_Key => m_Wrapper.m_general_f_Key;
        public InputAction @g_key => m_Wrapper.m_general_g_key;
        public InputAction @t_key => m_Wrapper.m_general_t_key;
        public InputAction @i_key => m_Wrapper.m_general_i_key;
        public InputAction @b_key => m_Wrapper.m_general_b_key;
        public InputAction @m_key => m_Wrapper.m_general_m_key;
        public InputAction @n_key => m_Wrapper.m_general_n_key;
        public InputAction @x_key => m_Wrapper.m_general_x_key;
        public InputAction @c_key => m_Wrapper.m_general_c_key;
        public InputAction @v_key => m_Wrapper.m_general_v_key;
        public InputActionMap Get() { return m_Wrapper.m_general; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @action.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnAction;
                @action.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnAction;
                @action.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnAction;
                @cancel.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnCancel;
                @cancel.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnCancel;
                @cancel.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnCancel;
                @buttonWest.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonWest;
                @buttonWest.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonWest;
                @buttonWest.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonWest;
                @buttonNorth.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonNorth;
                @buttonNorth.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonNorth;
                @buttonNorth.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonNorth;
                @buttonEast.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonEast;
                @buttonEast.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonEast;
                @buttonEast.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonEast;
                @oneKey.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnOneKey;
                @oneKey.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnOneKey;
                @oneKey.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnOneKey;
                @twoKey.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnTwoKey;
                @twoKey.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnTwoKey;
                @twoKey.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnTwoKey;
                @threeKey.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnThreeKey;
                @threeKey.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnThreeKey;
                @threeKey.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnThreeKey;
                @fourKey.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFourKey;
                @fourKey.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFourKey;
                @fourKey.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFourKey;
                @space.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSpace;
                @space.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSpace;
                @space.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSpace;
                @f_Key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnF_Key;
                @f_Key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnF_Key;
                @f_Key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnF_Key;
                @g_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnG_key;
                @g_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnG_key;
                @g_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnG_key;
                @t_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnT_key;
                @t_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnT_key;
                @t_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnT_key;
                @i_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnI_key;
                @i_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnI_key;
                @i_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnI_key;
                @b_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnB_key;
                @b_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnB_key;
                @b_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnB_key;
                @m_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnM_key;
                @m_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnM_key;
                @m_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnM_key;
                @n_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnN_key;
                @n_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnN_key;
                @n_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnN_key;
                @x_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnX_key;
                @x_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnX_key;
                @x_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnX_key;
                @c_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnC_key;
                @c_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnC_key;
                @c_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnC_key;
                @v_key.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnV_key;
                @v_key.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnV_key;
                @v_key.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnV_key;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @action.started += instance.OnAction;
                @action.performed += instance.OnAction;
                @action.canceled += instance.OnAction;
                @cancel.started += instance.OnCancel;
                @cancel.performed += instance.OnCancel;
                @cancel.canceled += instance.OnCancel;
                @buttonWest.started += instance.OnButtonWest;
                @buttonWest.performed += instance.OnButtonWest;
                @buttonWest.canceled += instance.OnButtonWest;
                @buttonNorth.started += instance.OnButtonNorth;
                @buttonNorth.performed += instance.OnButtonNorth;
                @buttonNorth.canceled += instance.OnButtonNorth;
                @buttonEast.started += instance.OnButtonEast;
                @buttonEast.performed += instance.OnButtonEast;
                @buttonEast.canceled += instance.OnButtonEast;
                @oneKey.started += instance.OnOneKey;
                @oneKey.performed += instance.OnOneKey;
                @oneKey.canceled += instance.OnOneKey;
                @twoKey.started += instance.OnTwoKey;
                @twoKey.performed += instance.OnTwoKey;
                @twoKey.canceled += instance.OnTwoKey;
                @threeKey.started += instance.OnThreeKey;
                @threeKey.performed += instance.OnThreeKey;
                @threeKey.canceled += instance.OnThreeKey;
                @fourKey.started += instance.OnFourKey;
                @fourKey.performed += instance.OnFourKey;
                @fourKey.canceled += instance.OnFourKey;
                @space.started += instance.OnSpace;
                @space.performed += instance.OnSpace;
                @space.canceled += instance.OnSpace;
                @f_Key.started += instance.OnF_Key;
                @f_Key.performed += instance.OnF_Key;
                @f_Key.canceled += instance.OnF_Key;
                @g_key.started += instance.OnG_key;
                @g_key.performed += instance.OnG_key;
                @g_key.canceled += instance.OnG_key;
                @t_key.started += instance.OnT_key;
                @t_key.performed += instance.OnT_key;
                @t_key.canceled += instance.OnT_key;
                @i_key.started += instance.OnI_key;
                @i_key.performed += instance.OnI_key;
                @i_key.canceled += instance.OnI_key;
                @b_key.started += instance.OnB_key;
                @b_key.performed += instance.OnB_key;
                @b_key.canceled += instance.OnB_key;
                @m_key.started += instance.OnM_key;
                @m_key.performed += instance.OnM_key;
                @m_key.canceled += instance.OnM_key;
                @n_key.started += instance.OnN_key;
                @n_key.performed += instance.OnN_key;
                @n_key.canceled += instance.OnN_key;
                @x_key.started += instance.OnX_key;
                @x_key.performed += instance.OnX_key;
                @x_key.canceled += instance.OnX_key;
                @c_key.started += instance.OnC_key;
                @c_key.performed += instance.OnC_key;
                @c_key.canceled += instance.OnC_key;
                @v_key.started += instance.OnV_key;
                @v_key.performed += instance.OnV_key;
                @v_key.canceled += instance.OnV_key;
            }
        }
    }
    public GeneralActions @general => new GeneralActions(this);
    public interface IGeneralActions
    {
        void OnAction(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnButtonWest(InputAction.CallbackContext context);
        void OnButtonNorth(InputAction.CallbackContext context);
        void OnButtonEast(InputAction.CallbackContext context);
        void OnOneKey(InputAction.CallbackContext context);
        void OnTwoKey(InputAction.CallbackContext context);
        void OnThreeKey(InputAction.CallbackContext context);
        void OnFourKey(InputAction.CallbackContext context);
        void OnSpace(InputAction.CallbackContext context);
        void OnF_Key(InputAction.CallbackContext context);
        void OnG_key(InputAction.CallbackContext context);
        void OnT_key(InputAction.CallbackContext context);
        void OnI_key(InputAction.CallbackContext context);
        void OnB_key(InputAction.CallbackContext context);
        void OnM_key(InputAction.CallbackContext context);
        void OnN_key(InputAction.CallbackContext context);
        void OnX_key(InputAction.CallbackContext context);
        void OnC_key(InputAction.CallbackContext context);
        void OnV_key(InputAction.CallbackContext context);
    }
}
